server:
  port: ${PORT:0}

spring:
  application:
    name: pm-company-ws

  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/project_management_company
    username: developer
    password: dev123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update